### ISSUE TITLE
Zenodo JATS XML file

### ISSUE THREAD

**Issue by kelle** [arceli/charter#40]
@AramZS needs an example JATS XML file for submitting the actual content to Zenodo. @lnielsen ?

**Comment by LibrarPotter** [comment]
JATS XML version 1.1 official documentation:
http://jats.nlm.nih.gov/archiving/

Customization style sheets for turning JATS XML version 1.0 documents into HTML or PDF:
https://github.com/ncbi/JATSPreviewStylesheets

For information about a conversion from Markdown to JATS XML (version 1.0) using Pandoc see: http://blog.martinfenner.org/2013/12/12/from-markdown-to-jats-xml-in-one-step/
Or his github repo with the code: https://github.com/mfenner/pandoc-jats
I know this isn't for going from HTML to JATS XML, which we were talking about, but it is an example of automated conversion.

Here's an example of JATS XML version 1.0 (change the file extension to .xml instead of .txt to view correctly):
[exampleOfJATSXML_changeTheFileTypeToXML.txt](https://github.com/arceli/charter/files/252834/exampleOfJATSXML_changeTheFileTypeToXML.txt)

**Comment by kelle** [comment]
Questions (Kelle is working on these):
- do we need corresponding author?
- what is the ext-link format
- syntax for the graphic tag

**Comment by kelle** [comment]
Every link in the article needs to be enclosed in `<ext-link>`. This attribute takes lots of things (http://jats.nlm.nih.gov/archiving/tag-library/1.1/element/ext-link.html) but we will keep it simple:

```
<ext-link ext-link-type="uri" xlink:href="https://github.com/" 
xlink:type="simple">Github</ext-link>
```

**Comment by AramZS** [comment]
Do we need to care about the leading Boxed text section in the example?

```
<sec>
    <title/><boxed-text>
    <p>This paper in markdown format was written by Ethan White et al. The markdown file and the associated bibliogaphy and figure files are available from the <ext-link ext-link-type="uri" xlink:href="https://github.com/weecology/data-sharing-paper" xlink:type="simple">Github repository of the paper</ext-link>.</p>
    </boxed-text>

    <boxed-text>
    <p>I used <ext-link ext-link-type="uri" xlink:href="https://github.com/weecology/data-sharing-paper/commit/b5a73eb0942a18bb29810025a528aea48a8465e7" xlink:type="simple">this</ext-link> version, an earlier version was published as <ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.7287/peerj.preprints.7v1" xlink:type="simple">PeerJ Preprint</ext-link>. Special thanks to Ethan White for allowing me to reuse this paper. The paper is used here as an example document to show how markdown can handle scholarly documents, in particular tables, figures and citations. The document was slightly modified from the orginal: added YAML frontmatter (needed by jekyll, author names are also stored there), and changed the anchor text for some links. This post is using the APA citation style. Please restrict your comments to issues related to Scholarly Markdown, for the content of the article contact Ethan directly.</p>
    </boxed-text>

    </sec>
```

**Comment by kelle** [comment]
images should be inside a <fig> and <graphic> is used to point to the file.
http://jats.nlm.nih.gov/archiving/tag-library/1.1/chapter/tag-fig-graphic.html
Simplest example:

```
<fig id="fg-012">
<label>Figure 12.</label>
<caption>
<title>My Dog</title>
<p>He is so sweet! This is his best pose.</p>
</caption>
<graphic xlink:href="frontView.png"/>
</fig>
```

**Comment by kelle** [comment]
- We don't need to mark corresponding author.
- I don't think we need to do anything with `<boxed-text>`.

**Comment by kelle** [comment]
I'm pretty sure this is all done.
