### ISSUE TITLE
Unaccepted Content

### ISSUE THREAD

**Issue by kelle** [arceli/charter#6]
In trying to fill in the excellent outline @jonathansick started, I realized it would be easier to think about what we don't want to accept instead of what we will. 

And I'm not sure about this, but I don't think we want to accept things which feel like the belong on the arxiv. But I don't know how to phrase this. I think we would like to accept scientific results, but only if they are presented in an informal way, e.g., as a blog post. So, maybe the wording is that we accept "brief descriptions of scientific results, insights, or musings".

But will we accept posters and talks from conferences that are choosing not to do proceedings? I vote no. I think conferences should be pressured/encouraged to make their own Zenodo communities and moderate their own submissions. 

I do however think we should accept talk slides from colloquia and non-astro conferences that are relevant to the wider astro community....e.g., maybe slides from SciPy conferences, AAAS meetings, etc. I just saw some slides posted on slideshare about incorporating data science into the UC curriculum. I think that would be an appropriate submission.

Do we require the content to have been published or presented elsewhere first? E.g., on a blog. Or can someone just write something and submit directly to the archive? I don't know what I think about this but lean towards this being an archive, not a publication vehicle.

**Comment by owlice** [comment]
"I don't think we want to accept things which feel like the belong on the arxiv"
I agree, and your phrasing is good. 

I also agree on not accepting posters and conference talks. I disagree about accepting slides from colloquia and non-astro conferences, however. I'd like to see those who organize colloquia create a community for them along the same lines as this community. That's a different type of scholarly/academic communication than "brief descriptions of scientific results, insights, or musings".

Conferences should have their own communities, just as you've already said! "I think conferences should be pressured/encouraged to make their own Zenodo communities and moderate their own submissions." Goes for non-astro conferences as well as astro. 

And content should have been published elsewhere; I agree with that, too. I think this should definitely be an archive. We can always suggest that those who want to submit unpublished work here contribute a guest post to one or another of the accepted blogs, and then archive that. :-D

**Comment by owlice** [comment]
Well, maybe okay on slide sets; I could probably be persuaded on that point. I'd still like those running colloquia to band together to provide an archive/community, but those presenting shouldn't be penalized by non-entry if colloquia do not do so.

**Comment by jonathansick** [comment]
Anything that could get a proper citation elsewhere (such as a conference proceeding that ought to be indexed by ADS, or something submitted to the archive) should be excluded from the AIAC. _AIAC is a refuge of the currently uncitable._

Non-conference talks (and non-academic talks, like at tech conferences) ought to be encouraged. I may live to see the day when each Astronomy department across the world has a Zenodo-like community for their brownbag lunch talks, but I doubt it.

For prior web publication, I vote yes. The AIAC is for things that you've **published** and now just want to have archived and indexed for the community.

In a future README for the AIAC we ought to point people with conference posters/talks/proceedings to emulate @libcce's workflow:
- https://zenodo.org/collection/user-hitran-13
- http://altbibl.io/gazette/open-access-publishing-made-easy-for-conferences/
- http://adsabs.harvard.edu/abs/2014hitr.confE..60A

---

My only qualm with @kelle's statement 

> I think we would like to accept scientific results, but only if they are presented in an informal way, e.g., as a blog post. So, maybe the wording is that we accept "brief descriptions of scientific results, insights, or musings".

Is that we ought to also encourage both _scientific_ and _technical_ discussion of software/statistics/data science topics because that discussion is probably most marginalized from the journals. I'm not an instrumentalist, but maybe they also feel the same way at times(?)

We also want to leave room for sociological discussions of the field (women in astronomy, career paths for astronomers.... right?)

**Comment by jonathansick** [comment]
And what do we do about astrobites.org? It's amazing, but it's also essentially readable summaries of papers. I'd say the readable summary ought to be indexed, but I just wanted to have a consensus of how we feel about 'secondary research'.

**Comment by owlice** [comment]
I think Astrobites should have its own community under the umbrella of this effort if it wants one, so yes, I agree with you!

**Comment by kelle** [comment]
+1 for including AstroBites. but this also opens the realms to other folks science summaries. We can play this by ear...

As i mentioned is a previous thread, I think talking about "sub communities" is not something that's supported in the Zenodo infrastructure. And I think is over-granulizing. Either you make the _one_ place the AIAC Community or you ask AstroBites/AstroBetter to be essentially be their own journal. And ask ADS to index multiple communities. I vote for _one_ community, the Archive, which accepts blog content.

That all said, the idea of having essentially an AstroBetter journal with it's own unique ADS bibcode is quite attractive. And does have merit.

**Comment by owlice** [comment]
I just looked at the Charter again and have bolded the point about community-in-a-community below. 

There is an "Archive of Informal Astronomy Communications" (working name);
The Archive has an Editor and Board that is backed by astronomy libraries and the AAS or similar organizations,
The Archive is fundamentally a Zenodo curated community,
ADS agrees to index the resources of this Zenodo community,
Online Publishers (such as a blog) apply for affiliation with the Archive. **Each affiliated Publisher gains its own community within the umbrella AIAC community. This allows for self-moderation by Publishers while also giving oversight to AIAC. (Note: this community-in-a-community structure is an upcoming Zenodo feature).**
There is probably a way to devise the bibcode so it denotes in which community an entry resides, essentially giving each community within the larger structure its own bibcode.

**Comment by aaccomazzi** [comment]
Hey, sorry for coming late to the party, hand to deal with proposal writing for the past week.  Couple of things worth mentioning, off the top of my head.

I think it's worth asking the question now: is Arceli a alt-publication or an archive of alt-publications?  It sounds to me like it should be the latter, in which case we may want to consider a rule that says that the content is selected by the editors (based on well-specified policies), and is then archived and curated in Zenodo.  The curation should be very lightweight: make sure the proper people are acknowledged as authors; come up with an abstract if one isn't available; use well-established keywords to categorize the content both by subject area and by media type (e.g. "cosmology", "blog entry").  All of this will come in handy both at the Zenodo level (for filtering) and at the ADS level (for searching).

The second thing to mention is that while I like where this is going, we have to be clear about what the ADS "deal" is: we are interested in scholarly content appropriate for astronomers.  To the extent that this is the bar to make it into Arceli, then there are no problems.  But if we start throwing in the kitchen sink then, well, we may need to have some content filtering on our side, which would really suck since it's more work for us and more frustrating for the users and editors ("why can't I find my blog post in ADS?").  So let's agree and agree early on what belongs in there and then live happily ever after.  

Last thing: please don't get too hung up on bibcodes or other identifiers associated with these entries.  The bibcode model is broken now that articles do not appear in volumes any longer and "page" numbers are 7-digit ids.  Trying to cram semantics into a 19-digit string is hopeless, and we won't be able to make everybody happy even if we tried.  I suggest having the "bibstem" or journal abbreviation, indicate what the publication is, and then sequential identifiers for pseudo-volume/page.  Any slicing based on sub-communities can be done via keywords, or publication type.  Even if we could have "pretty looking" bibcodes, the average user wouldn't make much sense of them anyways.

**Comment by kelle** [comment]
incorporated into Charter
https://github.com/arceli/charter/blob/master/README.md#topics
https://github.com/arceli/charter/blob/master/README.md#media
